# Generated by Django 2.0.7 on 2019-07-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('event_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
                ('level_fluent', models.CharField(choices=[('mother_tongue', 'Native Speak'), ('near_native', 'Fluent'), ('exclt_command', 'Highly proficient in spoken and written'), ('good_command', 'Good working knowledge'), ('working_knowledge', 'basic communication skills')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=130)),
                ('training_type', models.CharField(max_length=30)),
                ('training_url', models.CharField(max_length=1000)),
                ('training_complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VolEmgtCtct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_last_name', models.CharField(max_length=30)),
                ('e_first_name', models.CharField(max_length=30)),
                ('e_address', models.CharField(max_length=50)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('physical_limitations', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5)),
                ('physical_explanation', models.TextField(blank=True, null=True)),
                ('street_address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=40)),
                ('notes', models.CharField(max_length=600)),
                ('cross_cultural_experiences', models.CharField(max_length=600)),
                ('why_FDPs', models.CharField(max_length=600)),
                ('spirituality', models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='volemgtctct',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='training',
            name='volunteers',
            field=models.ManyToManyField(to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='role',
            name='trainings',
            field=models.ManyToManyField(to='volunteers.Training'),
        ),
        migrations.AddField(
            model_name='role',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='organizationaffiliation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='language',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='interest',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
    ]
