# Generated by Django 2.2.2 on 2019-06-23 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1, 'Please enter a valid name.')])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1, 'Please enter a valid name.')])),
                ('middle_name', models.CharField(max_length=30)),
                ('birth_date', models.DateTimeField(verbose_name='Date of birth')),
                ('physical_limitations', models.IntegerField(default=0)),
                ('physical_explanation', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Please enter a valid address.')])),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, 'Please enter a valid state abbreviation.')])),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5, 'Please enter a valid zipcode.')])),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7, 'Please enter a valid phone number (xxx-xxx-xxxx).')])),
                ('email', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4, 'Please enter a valid email.')])),
                ('emergency_last_name', models.CharField(max_length=30)),
                ('emergency_first_name', models.CharField(max_length=30)),
                ('emergency_address', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7, 'Please enter a valid phone number (xxx-xxx-xxxx).')])),
                ('notes', models.CharField(max_length=600)),
                ('cross_cultural_experiences', models.CharField(max_length=600)),
                ('why_FDPs', models.CharField(max_length=600)),
                ('spirituality', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('training_url', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('training_complete', models.IntegerField(default=0)),
                ('volunteers', models.ManyToManyField(to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('trainings', models.ManyToManyField(to='volunteers.Training')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Please enter a valid organization name.')])),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
                ('level_fluent', models.IntegerField(default=0)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=50)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, 'Please enter a valid event name.')])),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('event_description', models.CharField(max_length=200)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
    ]
